### ISSUE TITLE
How do you judge the degree of difficulty?

### ISSUE THREAD

**Issue by FuZer** [hunkim/KaggleZeroToAll#6]
According to Kaggle problem directory naming rule, I need to give the directory a name for the degree of difficulty. However, this is very ambiguous standards. Is there any more specific standard?

**Comment by kkweon** [comment]
Currently, **it's totally up to you** because 

1. It's hard to judge difficulty based on a problem only. Two people can solve the same problem very differently. One can just run `model.fit(X, y)` while others may have an advanced level of knowledge.

2. It's a sort of relative score (like `A` is more difficult than `B`) but, since we yet to have many problems solved, you can go with 5 (which is normal) and not worry about it until more solutions come up.

3. Personally, I think we should narrow down its range (as of now, 0 being the easiest to 9 being the most difficult). Instead of 0-9, "easy/normal/difficult" should do the job.

**Comment by FuZer** [comment]
Okay. Thank you for your comment. I'll end this issue.
